const $ = (id) => document.getElementById(id);
const storage = {name:'raketnaPostevankaIme',age:'raketnaPostevankaStarost',avatar:'raketnaPostevankaAvatar',collection:'raketnaPostevankaZbirka',missed:'raketnaPostevankaZgreseniRacuni',practice:'raketnaPostevankaTezavniRacuni',recent:'raketnaPostevankaZadnjiRacuni',score:'raketnaPostevankaSkupneTocke'};
const travelItems = {
  diamond:[{id:'wormhole-crystal',emoji:'💎',name:'Kristal za črvino',description:'Raketi odpre bližnjico skozi vesolje.'},{id:'moon-gem',emoji:'🔷',name:'Lunin dragulj',description:'Na temni strani lune sveti kot zvezda.'},{id:'nebula-pearl',emoji:'🫧',name:'Meglični biser',description:'V sebi skriva bleščeč oblak zvezdnega prahu.'},{id:'cosmic-ring',emoji:'💠',name:'Kozmični prstan',description:'Z njim se raketa varno vrne domov.'},{id:'ice-crystal',emoji:'🧊',name:'Kristal ledenega planeta',description:'Ohladi raketo med vročimi zvezdami.'},{id:'starlight',emoji:'✨',name:'Zvezdna iskra',description:'Vodi odpravo skozi temno meglico.'},{id:'space-pearl',emoji:'🪩',name:'Biser vesolja',description:'Zablesti ob vsakem velikem odkritju.'},{id:'aurora-stone',emoji:'🔹',name:'Kamen polarnega sija',description:'V njem plešejo barve oddaljenih planetov.'},{id:'meteor-jewel',emoji:'☄️',name:'Meteorski dragulj',description:'Priletel je naravnost iz zvezdnega dežja.'},{id:'portal-stone',emoji:'🔮',name:'Kamen portala',description:'Pozna skrivne poti med galaksijami.'}],
  gold:[{id:'star-compass',emoji:'🧭',name:'Zvezdni kompas',description:'Pokaže smer do najbolj oddaljenih planetov.'},{id:'turbo-fuel',emoji:'⛽',name:'Turbo gorivo',description:'Raketi doda poseben zvezdni pospešek.'},{id:'space-key',emoji:'🗝️',name:'Ključ do galaksije',description:'Odpira skrivna vrata med zvezdami.'},{id:'satellite',emoji:'🛰️',name:'Mali satelit',description:'Pošilja novice z vseh koncev vesolja.'},{id:'helmet',emoji:'⛑️',name:'Astronavtska čelada',description:'Varuje glavo na sprehodu po luni.'},{id:'solar-panel',emoji:'🔋',name:'Sončna baterija',description:'Napolni raketo s svetlobo zvezd.'},{id:'rocket-engine',emoji:'⚙️',name:'Zvezdni motor',description:'Daje raketi moč za dolge skoke.'},{id:'moon-flag',emoji:'🚩',name:'Zastavica odprave',description:'Označi novoodkrit planet.'},{id:'space-radio',emoji:'📡',name:'Vesoljski radio',description:'Ujame pozdrave prijaznih astronavtov.'},{id:'planet-pass',emoji:'🎫',name:'Vstopnica za Saturn',description:'Omogoči obisk planetov z obroči.'}],
  silver:[{id:'star-map',emoji:'🗺️',name:'Zemljevid zvezd',description:'Na njem so narisane poti čez vesolje.'},{id:'telescope',emoji:'🔭',name:'Daljnogled za planete',description:'Z njim opaziš tudi čisto majhne lune.'},{id:'camera',emoji:'📷',name:'Fotoaparat za spomine',description:'Shrani najlepše utrinke s poti.'},{id:'gloves',emoji:'🧤',name:'Rokavice za komete',description:'Ogrejejo roke na ledenih planetih.'},{id:'notebook',emoji:'📓',name:'Dnevnik odprave',description:'Vanjo zapišeš nova odkritja.'},{id:'water',emoji:'🫗',name:'Steklenička vode',description:'Osveži raziskovalce na dolgih poteh.'},{id:'binoculars',emoji:'🔍',name:'Povečevalno steklo',description:'Pomaga raziskati skrivnostne kamne.'},{id:'rope',emoji:'🪢',name:'Vrv za sprehod v breztežnosti',description:'Drži odpravo skupaj blizu rakete.'},{id:'blanket',emoji:'🧣',name:'Topel vesoljski šal',description:'Za udobje med čakanjem na zvezdni vlak.'},{id:'lunchbox',emoji:'🍱',name:'Zvezdna malica',description:'Daje energijo za naslednji račun.'}],
  bronze:[{id:'backpack',emoji:'🎒',name:'Pustolovski nahrbtnik',description:'Vanjo spakiraš vse za vesoljsko pot.'},{id:'snack',emoji:'🥪',name:'Malica za na pot',description:'Zvezdni popotniki potrebujejo energijo.'},{id:'lantern',emoji:'🔦',name:'Svetilka za kraterje',description:'Osvetli temne kote na novih planetih.'},{id:'boots',emoji:'🥾',name:'Čevlji za luno',description:'Pustijo čisto posebne odtise v luninem prahu.'},{id:'wrench',emoji:'🔧',name:'Ključ za raketo',description:'Pritegne vsak majav vijak na poti.'},{id:'first-aid',emoji:'🩹',name:'Komplet prve pomoči',description:'Za male praske na veliki odpravi.'},{id:'magnifier',emoji:'🔎',name:'Lupa za kamenčke',description:'Pokaže drobne kristale na planetih.'},{id:'apple',emoji:'🍎',name:'Jabolko za pogum',description:'Hrustljava malica za pogumne astronavte.'},{id:'cap',emoji:'🧢',name:'Kapa poveljnice',description:'Pokaže, kdo vodi odpravo.'},{id:'toolbox',emoji:'🧰',name:'Škatla z orodjem',description:'V njej je vse za hitro popravilo.'}]
};
const tierInfo = {diamond:{label:'💎 DIAMANTNI',reward:'💎 DIAMANTNI PREDMET'},gold:{label:'🥇 ZLATI',reward:'🥇 ZLATI PREDMET'},silver:{label:'🥈 SREBRNI',reward:'🥈 SREBRNI PREDMET'},bronze:{label:'🥉 BRONASTI',reward:'🥉 BRONASTI PREDMET'}};
travelItems.silver.push(
  {id:'space-clock',emoji:'⏱️',name:'Vesoljska ura',description:'Meri čas do naslednjega velikega skoka.'},{id:'star-pillow',emoji:'🛏️',name:'Zvezdna blazina',description:'Za kratek počitek med planeti.'},{id:'magic-pencil',emoji:'✏️',name:'Svinčnik za zemljevide',description:'Z njim narišeš še neodkrite poti.'},{id:'raincoat',emoji:'🧥',name:'Plašč za meteorski dež',description:'Ohrani odpravo suho med zvezdnimi plohami.'},{id:'space-plant',emoji:'🪴',name:'Rastlinica iz Marsa',description:'Razveseli kabino rakete z zelenjem.'},{id:'moon-cup',emoji:'🥤',name:'Lunin lonček',description:'V njem se sok ne razlije niti v breztežnosti.'},{id:'headphones',emoji:'🎧',name:'Slušalke za signale',description:'Ujamejo nežne zvoke oddaljenih planetov.'},{id:'star-stickers',emoji:'🏷️',name:'Nalepke zvezd',description:'Z njimi označiš najljubše odkritje.'},{id:'pocket-mirror',emoji:'🪞',name:'Žepno ogledalce',description:'Pomaga preveriti čelado pred izstopom.'},{id:'travel-book',emoji:'📕',name:'Knjiga planetov',description:'Polna je zgodb o čudnih vesoljskih bitjih.'}
);
travelItems.bronze.push(
  {id:'space-socks',emoji:'🧦',name:'Vesoljske nogavice',description:'Ogrejejo prste na mrzli luni.'},{id:'cookie',emoji:'🍪',name:'Piškot za astronavte',description:'Sladka energija za hitro računanje.'},{id:'umbrella',emoji:'☂️',name:'Dežnik za asteroide',description:'Zelo majhen, a prav zabaven na poti.'},{id:'compass-sticker',emoji:'🧷',name:'Sponka za zemljevid',description:'Drži zemljevid varno pritrjen v raketi.'},{id:'space-brush',emoji:'🪥',name:'Zvezdna ščetka',description:'Poskrbi za bleščeč nasmeh na fotografijah.'},{id:'mug',emoji:'☕',name:'Topel lonček',description:'Za kakav med gledanjem zvezd.'},{id:'puzzle',emoji:'🧩',name:'Košček uganke',description:'Morda sodi v zemljevid skrivnega planeta.'},{id:'paint',emoji:'🎨',name:'Barve meglice',description:'Z njimi pobarvaš vesoljski dnevnik.'},{id:'drum',emoji:'🥁',name:'Boben za vzlet',description:'Z njim naznaniš začetek odprave.'},{id:'kite',emoji:'🪁',name:'Zmajček brez vetra',description:'V breztežnosti leti čisto sam.'},{id:'shell',emoji:'🐚',name:'Školjka z oceanskega planeta',description:'V njej šumi oddaljeno vesoljsko morje.'},{id:'spoon',emoji:'🥄',name:'Žlička za zvezdni sladoled',description:'Prav pride na vročem Merkurju.'},{id:'bell',emoji:'🔔',name:'Zvonec za signal',description:'Opozori posadko, da je čas za vzlet.'},{id:'balloon',emoji:'🎈',name:'Balon za veselje',description:'Praznuje vsak uspešen račun.'},{id:'leaf',emoji:'🍃',name:'List z Venerinega vrta',description:'Je lahek kot zvezdni prah.'},{id:'crayon',emoji:'🖍️',name:'Kreda za kraterje',description:'Z njo rišeš poti po luninih tleh.'},{id:'paper-plane',emoji:'✈️',name:'Papirnato letalo',description:'V kabini rakete kroži brez prestanka.'},{id:'badge',emoji:'📛',name:'Značka raziskovalke',description:'Pokaže, kdo rad odkriva novo.'},{id:'ticket',emoji:'🎟️',name:'Vozovnica za raketo',description:'Dovoljuje vstop na naslednjo odpravo.'},{id:'toy-robot',emoji:'🤖',name:'Mali robot pomočnik',description:'Pomaga iskati izgubljene vijake.'}
);
let playerName = (localStorage.getItem(storage.name) || '').trim();
let playerAge = Number(localStorage.getItem(storage.age) || 0);
let playerAvatar = localStorage.getItem(storage.avatar) || '🧑‍🚀';
let storedCollection = JSON.parse(localStorage.getItem(storage.collection) || '[]');
const legacyCollection = [{tier:'silver',id:'star-map'},{tier:'gold',id:'star-compass'},{tier:'bronze',id:'backpack'},{tier:'bronze',id:'snack'},{tier:'silver',id:'camera'},{tier:'silver',id:'telescope'},{tier:'bronze',id:'lantern'},{tier:'gold',id:'turbo-fuel'}];
let collected = Array.isArray(storedCollection) ? storedCollection.map(item=>typeof item==='number'?legacyCollection[item%legacyCollection.length]:item).filter(item=>item && typeof item==='object' && travelItems[item.tier]?.some(travel=>travel.id===item.id)) : [];
let missedFacts = JSON.parse(localStorage.getItem(storage.missed) || '{}');
missedFacts = missedFacts && typeof missedFacts==='object' && !Array.isArray(missedFacts) ? missedFacts : {};
const multiplicationFacts = Array.from({length:10},(_,a)=>Array.from({length:10-a},(_,offset)=>({a:a+1,b:a+offset+1,answer:(a+1)*(a+offset+1),key:`m:${a+1}x${a+offset+1}`}))).flat();
const divisionFacts = Array.from({length:10},(_,divisor)=>Array.from({length:10},(_,quotient)=>({a:(divisor+1)*(quotient+1),b:divisor+1,answer:quotient+1,key:`d:${(divisor+1)*(quotient+1)}÷${divisor+1}`}))).flat();
const allQuestionKeys = new Set([...multiplicationFacts,...divisionFacts].map(fact=>fact.key));
const storedPracticeScores = JSON.parse(localStorage.getItem(storage.practice) || 'null');
let practiceScores = storedPracticeScores && typeof storedPracticeScores==='object' && !Array.isArray(storedPracticeScores) ? Object.fromEntries(Object.entries(storedPracticeScores).filter(([key,score])=>allQuestionKeys.has(key)&&Number.isFinite(Number(score))&&Number(score)>0).map(([key,score])=>[key,Number(score)])) : Object.fromEntries(Object.entries(missedFacts).filter(([key,count])=>allQuestionKeys.has(key)&&Number(count)>0).map(([key,count])=>[key,Number(count)]));
let recentQuestions = JSON.parse(localStorage.getItem(storage.recent) || '[]');
recentQuestions = Array.isArray(recentQuestions) ? recentQuestions.map(key=>String(key).includes(':')?String(key):`m:${key}`).filter(key=>allQuestionKeys.has(key)).slice(-30) : [];
const diamondStep = 3000;
let totalScore = Number(localStorage.getItem(storage.score) || 0);
const state = { askedKeys:new Set(), mode:'multiply', seconds:15, multiplier:1, timeless:false, difficulty:'Mirno', maxRounds:10, score:0, streak:0, best:0, lives:3, correct:0, round:0, active:false, locked:false, sound:true, timer:null, startTime:0, a:0, b:0, answer:0, currentKey:'', rewards:[], roundMisses:[] };
function refreshPlayerUI(){document.title='Raketna poštevanka';$('playerAvatar').textContent=playerAvatar;$('cardName').textContent=playerName;$('cardAge').textContent=`${playerAge} let`;}
function randomCheer(){return ['Bravo!','Zvezdica ujeta!','Kako hitro!','Rakéta pospešuje!','Odlično računaš!'][Math.floor(Math.random()*5)];}
function renderCollection(){ $('collectionCount').textContent=`${collected.length} ${collected.length===1?'predmet':'predmetov'}`; $('collectionItems').innerHTML=Object.keys(travelItems).map(tier=>{const earned=collected.filter(item=>item.tier===tier);const items=earned.map(earnedItem=>travelItems[tier].find(item=>item.id===earnedItem.id)).map(item=>`<span class="travel-item" tabindex="0" aria-label="${item.name}. ${item.description}"><span aria-hidden="true">${item.emoji}</span><span class="item-tooltip"><b>${item.name}</b>${item.description}</span></span>`).join('');return `<div class="collection-tier"><span class="tier-label ${tier}">${tierInfo[tier].label}<small>${earned.length} / ${travelItems[tier].length}</small></span><div class="tier-items">${items||'<span class="empty-tier">še čaka</span>'}</div></div>`;}).join(''); }
function renderHomeStats(){ $('totalScore').textContent=totalScore; const remaining=diamondStep-(totalScore%diamondStep); $('pointsToDiamond').textContent=remaining; }
function awardTravelItem(requestedTier){ const tierOrder=requestedTier==='gold'?['gold','silver','bronze']:requestedTier==='silver'?['silver','bronze','gold']:requestedTier==='bronze'?['bronze','silver','gold']:['diamond'];const count=tier=>collected.filter(item=>item.tier===tier).length;const tier=tierOrder.find(candidate=>count(candidate)<travelItems[candidate].length);if(!tier)return;const alreadyEarned=count(tier),item=travelItems[tier][alreadyEarned];collected.push({tier,id:item.id});localStorage.setItem(storage.collection,JSON.stringify(collected));state.rewards.push({...item,tier});renderCollection();}
renderCollection();
renderHomeStats();
const numberGrid = $('numberGrid');
const rowHues = [205,225,250,275,305,335,12,42,88,160];
const difficultySeconds = {multiply:[15,11,7],divide:[12,8,4]};
function renderNumberGrid(maximum){numberGrid.innerHTML='';numberGrid.setAttribute('aria-label',`Izberi odgovor od 1 do ${maximum}`);for(let number=1;number<=maximum;number++){const button=document.createElement('button'),row=Math.floor((number-1)/10),column=(number-1)%10;button.type='button';button.className='number-tile';button.textContent=number;button.style.setProperty('--tile-hue',rowHues[row]);button.style.setProperty('--tile-light',`${88-column*3.4}%`);button.setAttribute('aria-label',`Odgovori ${number}`);button.onclick=()=>submitAnswer(number);numberGrid.append(button);}}
renderNumberGrid(100);
function updateDifficultyTimes(){document.querySelectorAll('.difficulty:not(.no-timer)').forEach((button,index)=>{const seconds=difficultySeconds[state.mode][index];button.dataset.seconds=seconds;button.querySelector('small').textContent=`${seconds} s · točke ×${button.dataset.multiplier.replace('.',',')}`;});const selected=document.querySelector('.difficulty.active');if(selected&&!state.timeless)state.seconds=Number(selected.dataset.seconds);}
document.querySelectorAll('.mode').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-checked','false')});btn.classList.add('active');btn.setAttribute('aria-checked','true');state.mode=btn.dataset.mode;updateDifficultyTimes();});
document.querySelectorAll('.difficulty').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.difficulty').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-checked','false')});btn.classList.add('active');btn.setAttribute('aria-checked','true');state.seconds=Number(btn.dataset.seconds);state.multiplier=Number(btn.dataset.multiplier);state.timeless=btn.dataset.timeless==='true';state.difficulty=btn.dataset.name;});
function show(id){['name','welcome','game','review','result'].forEach(s=>$(s).classList.toggle('hidden',s!==id));}
function sound(type){ if(!state.sound || !window.AudioContext) return; const ctx=new AudioContext(), osc=ctx.createOscillator(), gain=ctx.createGain(); osc.connect(gain);gain.connect(ctx.destination); const ok=type==='ok'; osc.frequency.setValueAtTime(ok?640:190,ctx.currentTime); if(ok)osc.frequency.exponentialRampToValueAtTime(960,ctx.currentTime+.12); gain.gain.setValueAtTime(.055,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.18);osc.start();osc.stop(ctx.currentTime+.18); }
function burst(ok=true){ const layer=$('burst'); const icons=ok?['⭐','✨','🌟','💫']:['💫','☁️']; for(let i=0;i<(ok?13:6);i++){const s=document.createElement('span');s.className='spark';s.textContent=icons[i%icons.length];s.style.left='50%';s.style.top='52%';s.style.setProperty('--x',`${(Math.random()-.5)*360}px`);s.style.setProperty('--y',`${(Math.random()-.5)*290}px`);layer.append(s);setTimeout(()=>s.remove(),800);} }
function weightedQuestion(pool){const totalWeight=pool.reduce((total,fact)=>total+1+(practiceScores[fact.key]||0)*3,0);let draw=Math.random()*totalWeight;for(const fact of pool){draw-=1+(practiceScores[fact.key]||0)*3;if(draw<0)return fact;}return pool[pool.length-1];}
function chooseQuestion(){const facts=state.mode==='divide'?divisionFacts:multiplicationFacts,unused=facts.filter(fact=>!state.askedKeys.has(fact.key)),question=weightedQuestion(unused);state.askedKeys.add(question.key);recentQuestions=[...recentQuestions,question.key].slice(-30);localStorage.setItem(storage.recent,JSON.stringify(recentQuestions));return question;}
function recordMissedQuestion(){missedFacts[state.currentKey]=(missedFacts[state.currentKey]||0)+1;practiceScores[state.currentKey]=(practiceScores[state.currentKey]||0)+1;localStorage.setItem(storage.missed,JSON.stringify(missedFacts));localStorage.setItem(storage.practice,JSON.stringify(practiceScores));}
function recordCorrectQuestion(){const score=practiceScores[state.currentKey]||0;if(!score)return;const nextScore=score-1;if(nextScore)practiceScores[state.currentKey]=nextScore;else delete practiceScores[state.currentKey];localStorage.setItem(storage.practice,JSON.stringify(practiceScores));}
function renderReview(){const activePrefix=state.mode==='divide'?'d:':'m:',hardest=Object.entries(missedFacts).map(([key,count])=>{const normalized=key.includes(':')?key:`m:${key}`,isDivision=normalized.startsWith('d:'),parts=normalized.slice(2).split(isDivision?'÷':'x').map(Number),result=isDivision?parts[0]/parts[1]:parts[0]*parts[1];return {a:parts[0],b:parts[1],count,result,operator:isDivision?'÷':'×',key:normalized};}).filter(fact=>fact.key.startsWith(activePrefix)&&Number.isFinite(fact.result)).sort((first,second)=>second.count-first.count||second.result-first.result).slice(0,3);$('reviewIntro').textContent=hardest.length?'To so računi, ki so ti doslej povzročali največ težav. Poglej jih pred vzletom:':'Še nimaš zgrešenih računov — odličen začetek!';$('reviewList').innerHTML=hardest.length?hardest.map((fact,index)=>`<div class="review-card"><b>${index+1}</b><strong>${fact.a} ${fact.operator} ${fact.b} = ${fact.result}</strong><small>${fact.count}× zgrešeno</small></div>`).join(''):'<div class="review-empty">Pripravljen/-a si na novo odpravo! 🌟</div>';}
function newQuestion(){ if(state.round>=state.maxRounds){finish();return;} state.locked=false;state.round++;const question=chooseQuestion();state.a=question.a;state.b=question.b;state.answer=question.answer;state.currentKey=question.key;$('factorA').textContent=state.a;$('factorB').textContent=state.b;$('operator').textContent=state.mode==='divide'?'÷':'×';$('roundLabel').textContent=`RAČUN ${state.round} / ${state.maxRounds}`;$('difficultyLabel').textContent=state.difficulty.toUpperCase();$('answerInput').value='';$('answerInput').focus();$('cheerBubble').textContent=state.round===1?'Pripravljen/-a?':'Gremo!'; state.startTime=performance.now(); clearInterval(state.timer);if(state.timeless){$('timeText').textContent='∞';$('timerBar').style.width='100%';$('timerBar').classList.remove('time-danger');}else{state.timer=setInterval(tick,55);tick();} }
function tick(){if(!state.active)return;const left=Math.max(0,state.seconds-(performance.now()-state.startTime)/1000),pct=left/state.seconds;$('timeText').textContent=left.toFixed(1);$('timerBar').style.width=`${pct*100}%`;$('timerBar').classList.toggle('time-danger',pct<.3);if(left<=0) wrong(true);}
function redraw(){ $('score').textContent=String(state.score).padStart(3,'0');$('streak').textContent=state.streak;$('lives').textContent='❤️ '.repeat(state.lives)+'🩶 '.repeat(3-state.lives); }
function correct(){if(state.locked)return;state.locked=true;recordCorrectQuestion();const speed=state.timeless?0:Math.max(0,state.seconds-(performance.now()-state.startTime)/1000),points=state.timeless?0:Math.round((10+Math.ceil(speed*2)+state.streak*2)*state.multiplier);state.score+=points;state.streak++;state.best=Math.max(state.best,state.streak);state.correct++;redraw();clearInterval(state.timer);$('cheerBubble').textContent=randomCheer()+(points?` +${points}`:'');$('game').classList.add('correct-flash');setTimeout(()=>{$('game').classList.remove('correct-flash');newQuestion()},600);sound('ok');burst(true);}
function wrong(timeout=false){if(!state.active||state.locked)return;state.locked=true;recordMissedQuestion();state.roundMisses.push({a:state.a,b:state.b,answer:state.answer,operator:state.mode==='divide'?'÷':'×'});clearInterval(state.timer);state.lives--;state.streak=0;redraw();$('answerInput').classList.add('wrong-shake');$('cheerBubble').textContent=timeout?'Čas je potekel!':'Poskusi naslednjega!';sound('no');burst(false);setTimeout(()=>{$('answerInput').classList.remove('wrong-shake');if(state.lives<=0)finish();else newQuestion()},700);}
function submitAnswer(value){if(!state.active||state.locked)return;$('answerInput').value=value;if(Number(value)===state.answer)correct();else wrong();}
function start(){renderReview();show('review');}
function beginGame(){Object.assign(state,{askedKeys:new Set(),score:0,streak:0,best:0,lives:3,correct:0,round:0,active:true,locked:false,rewards:[],roundMisses:[]});renderNumberGrid(state.mode==='divide'?10:100);$('missionSummary').classList.add('hidden');redraw();show('game');newQuestion();}
function finish(){if(!state.active)return;state.active=false;clearInterval(state.timer);const previousTotal=totalScore;totalScore+=state.score;localStorage.setItem(storage.score,totalScore);const tier=state.correct===10?'gold':state.correct===9?'silver':state.correct===8?'bronze':null;if(state.round>=state.maxRounds&&tier) awardTravelItem(tier);const oldDiamonds=Math.floor(previousTotal/diamondStep),newDiamonds=Math.floor(totalScore/diamondStep);for(let step=oldDiamonds;step<newDiamonds;step++) awardTravelItem('diamond');renderHomeStats();$('summaryTitle').textContent=state.round>=state.maxRounds?'Misija končana!':'Rakéta se vrača domov!';const rewards=state.rewards.map(item=>`${item.emoji} ${item.name}`).join(' in ');$('summaryText').textContent=`${state.correct} / ${state.round} pravilnih · +${state.score} točk${rewards?` · Zbral/-a si: ${rewards}!`:''}`;if(state.rewards.length){const firstReward=state.rewards[0];$('result-title').textContent='Nov predmet!';$('resultMessage').textContent=state.rewards.length===1?'Odlično opravljena misija — ta oprema je zdaj tvoja!':'Neverjetno! Na tej misiji si našel/-la kar dve novi stvari.';$('rewardPanel').className=`reward-panel ${firstReward.tier}`;$('rewardTier').textContent=state.rewards.length===1?tierInfo[firstReward.tier].reward:'NOVE NAJDENE STVARI';$('rewardItems').innerHTML=state.rewards.map(item=>`<div class="reward-item"><b>${item.emoji}</b><strong>${item.name}</strong><small>${item.description}</small></div>`).join('');burst(true);}else{$('result-title').textContent='Škoda!';$('resultMessage').textContent=state.round>=state.maxRounds?'Za predmet potrebuješ vsaj 8 pravilnih odgovorov. Naslednjič ti bo uspelo!':'Raketi je zmanjkalo življenj. Vsak poskus je korak bliže do predmeta!';$('rewardPanel').className='reward-panel hidden';burst(false);}$('finalScore').textContent=state.score;$('bestStreak').textContent=`🔥 ${state.best}`;$('correctCount').textContent=`${state.correct} / ${state.round}`;$('roundMistakes').classList.toggle('hidden',!state.roundMisses.length);$('roundMistakeList').innerHTML=state.roundMisses.map(mistake=>`<span>${mistake.a} ${mistake.operator} ${mistake.b} = <b>${mistake.answer}</b></span>`).join('');show('result');window.scrollTo({top:0,behavior:'smooth'});}
function goHome(){state.active=false;clearInterval(state.timer);$('missionSummary').classList.remove('hidden');show('welcome');window.scrollTo({top:0,behavior:'smooth'});}
function saveProgress(){return {version:4,exportedAt:new Date().toISOString(),progress:{playerName,playerAge,playerAvatar,collection:collected,totalScore,missedFacts,practiceScores,recentQuestions}};}
function applyProgress(progress){const validCollection=Array.isArray(progress.collection)?progress.collection.filter(item=>item&&typeof item==='object'&&travelItems[item.tier]?.some(travel=>travel.id===item.id)):[];const validMisses=progress.missedFacts&&typeof progress.missedFacts==='object'&&!Array.isArray(progress.missedFacts)?Object.fromEntries(Object.entries(progress.missedFacts).filter(([key,count])=>allQuestionKeys.has(key)||allQuestionKeys.has(`m:${key}`)).map(([key,count])=>[key.includes(':')?key:`m:${key}`,Math.max(0,Number(count)||0)])):{};const validPractice=progress.practiceScores&&typeof progress.practiceScores==='object'&&!Array.isArray(progress.practiceScores)?Object.fromEntries(Object.entries(progress.practiceScores).filter(([key,score])=>allQuestionKeys.has(key)&&Number.isFinite(Number(score))&&Number(score)>0).map(([key,score])=>[key,Number(score)])):Object.fromEntries(Object.entries(validMisses).filter(([,count])=>count>0));const validRecent=Array.isArray(progress.recentQuestions)?progress.recentQuestions.map(key=>String(key).includes(':')?String(key):`m:${key}`).filter(key=>allQuestionKeys.has(key)).slice(-30):[];const importedName=typeof progress.playerName==='string'?progress.playerName.trim().slice(0,24):'';const importedAge=Number(progress.playerAge);const importedAvatar=avatarOptions.includes(progress.playerAvatar)?progress.playerAvatar:playerAvatar;collected=validCollection;totalScore=Math.max(0,Number(progress.totalScore)||0);missedFacts=validMisses;practiceScores=validPractice;recentQuestions=validRecent;if(importedName&&Number.isInteger(importedAge)&&importedAge>=3&&importedAge<=18){playerName=importedName;playerAge=importedAge;playerAvatar=importedAvatar;localStorage.setItem(storage.name,playerName);localStorage.setItem(storage.age,String(playerAge));localStorage.setItem(storage.avatar,playerAvatar);refreshPlayerUI();}localStorage.setItem(storage.collection,JSON.stringify(collected));localStorage.setItem(storage.score,totalScore);localStorage.setItem(storage.missed,JSON.stringify(missedFacts));localStorage.setItem(storage.practice,JSON.stringify(practiceScores));localStorage.setItem(storage.recent,JSON.stringify(recentQuestions));$('missionSummary').classList.add('hidden');renderCollection();renderHomeStats();}
const avatarOptions=['🧑‍🚀','👩‍🚀','👨‍🚀','🤖','🦊','🐼','🐱','🐶','🦄','🧙','🧚','🧑‍🎨','🦸','🧑‍🍳'];
document.querySelectorAll('.avatar-pick').forEach(button=>button.onclick=()=>{playerAvatar=button.dataset.avatar;document.querySelectorAll('.avatar-pick').forEach(pick=>{const active=pick===button;pick.classList.toggle('active',active);pick.setAttribute('aria-pressed',String(active));});});
function selectAvatar(avatar){playerAvatar=avatar;document.querySelectorAll('.avatar-pick').forEach(pick=>{const active=pick.dataset.avatar===avatar;pick.classList.toggle('active',active);pick.setAttribute('aria-pressed',String(active));});}
function openProfileEditor(){$('nameEyebrow').textContent='UREDI IZKAZNICO';$('name-title').innerHTML='Posodobi svojo<br /><em>vesoljsko izkaznico</em>';$('nameIntro').innerHTML='Spremeni ime, starost ali izberi<br />čisto nov avatar.';$('profileSubmitText').textContent='Shrani spremembe';$('nameInput').value=playerName;$('ageInput').value=playerAge;selectAvatar(playerAvatar);show('name');window.scrollTo({top:0,behavior:'smooth'});setTimeout(()=>$('nameInput').focus(),0);}
document.querySelectorAll('.avatar-pick').forEach(button=>button.onclick=()=>selectAvatar(button.dataset.avatar));
$('identityCard').onclick=openProfileEditor;
$('nameForm').onsubmit=event=>{event.preventDefault();const enteredName=$('nameInput').value.trim().slice(0,24),enteredAge=Number($('ageInput').value);if(!enteredName){$('nameInput').focus();return;}if(!Number.isInteger(enteredAge)||enteredAge<3||enteredAge>18){$('ageInput').focus();return;}playerName=enteredName;playerAge=enteredAge;localStorage.setItem(storage.name,playerName);localStorage.setItem(storage.age,String(playerAge));localStorage.setItem(storage.avatar,playerAvatar);refreshPlayerUI();renderCollection();show('welcome');};$('startBtn').onclick=start;$('againBtn').onclick=start;$('reviewStartBtn').onclick=beginGame;$('settingsBtn').onclick=goHome;$('backBtn').onclick=goHome;$('soundBtn').onclick=()=>{state.sound=!state.sound;$('soundBtn').textContent=state.sound?'♫':'×';$('soundBtn').classList.toggle('sound-on',state.sound)};$('exportProgressBtn').onclick=()=>{const blob=new Blob([JSON.stringify(saveProgress(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`ucni-napredek-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('importProgressBtn').onclick=()=>$('progressFileInput').click();$('progressFileInput').onchange=async event=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;try{const backup=JSON.parse(await file.text());if(![1,2,3,4].includes(backup?.version)||!backup.progress)throw new Error('Napačna datoteka');if(!confirm('Uvoz bo zamenjal izkaznico, predmete, točke in učni napredek. Nadaljujem?'))return;applyProgress(backup.progress);alert('Napredek je uspešno uvožen!');}catch{alert('Te datoteke ne morem prebrati kot učni napredek.');}};$('resetCollectionBtn').onclick=()=>{if(!confirm('Res želiš ponastaviti napredek? Izbrisani bodo vsi predmeti in skupne točke. Tega ne moreš razveljaviti.'))return;collected=[];totalScore=0;localStorage.removeItem(storage.collection);localStorage.removeItem(storage.score);$('missionSummary').classList.add('hidden');renderCollection();renderHomeStats();};$('answerForm').onsubmit=e=>{e.preventDefault();if($('answerInput').value!=='')submitAnswer($('answerInput').value);};if(playerName&&Number.isInteger(playerAge)&&playerAge>=3&&playerAge<=18&&avatarOptions.includes(playerAvatar)){refreshPlayerUI();renderCollection();show('welcome');}else{show('name');}
